"""Verse counts per chapter for the reference checker (ADR 0007: every verse exists).

Counted from the World English Bible in USFM (public domain, eBible.org), whose English
versification is the one OSIS references in our sources follow. Writes
packages/model/src/versification.ts; the output is committed, this script only
regenerates it.

Usage: python3 pipeline/build_versification.py && npx prettier --write packages/model/src/versification.ts
"""

import io
import pathlib
import re
import urllib.request
import zipfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "packages" / "model" / "src" / "versification.ts"
URL = "https://ebible.org/Scriptures/engwebp_usfm.zip"
# 1-2 Maccabees, which the Synodal Bible carries and some events cite: from the KJV with its
# Apocrypha (public domain), whose numbering the Synodal shares for these books.
DEUTERO_URL = "https://ebible.org/Scriptures/eng-kjv_usfm.zip"
DEUTERO = {"1MA": "1Macc", "2MA": "2Macc"}

USFM_TO_OSIS = {
    "GEN": "Gen", "EXO": "Exod", "LEV": "Lev", "NUM": "Num", "DEU": "Deut", "JOS": "Josh",
    "JDG": "Judg", "RUT": "Ruth", "1SA": "1Sam", "2SA": "2Sam", "1KI": "1Kgs", "2KI": "2Kgs",
    "1CH": "1Chr", "2CH": "2Chr", "EZR": "Ezra", "NEH": "Neh", "EST": "Esth", "JOB": "Job",
    "PSA": "Ps", "PRO": "Prov", "ECC": "Eccl", "SNG": "Song", "ISA": "Isa", "JER": "Jer",
    "LAM": "Lam", "EZK": "Ezek", "DAN": "Dan", "HOS": "Hos", "JOL": "Joel", "AMO": "Amos",
    "OBA": "Obad", "JON": "Jonah", "MIC": "Mic", "NAM": "Nah", "HAB": "Hab", "ZEP": "Zeph",
    "HAG": "Hag", "ZEC": "Zech", "MAL": "Mal", "MAT": "Matt", "MRK": "Mark", "LUK": "Luke",
    "JHN": "John", "ACT": "Acts", "ROM": "Rom", "1CO": "1Cor", "2CO": "2Cor", "GAL": "Gal",
    "EPH": "Eph", "PHP": "Phil", "COL": "Col", "1TH": "1Thess", "2TH": "2Thess", "1TI": "1Tim",
    "2TI": "2Tim", "TIT": "Titus", "PHM": "Phlm", "HEB": "Heb", "JAS": "Jas", "1PE": "1Pet",
    "2PE": "2Pet", "1JN": "1John", "2JN": "2John", "3JN": "3John", "JUD": "Jude", "REV": "Rev",
}

# Where the WEB's chapter lengths differ from the English versification OSIS references
# use: it moves the doxology of Romans to 14:24-26 (KJV and ESV keep it at 16:25-27),
# and like the KJV it stops 3 John at 14 and Revelation 12 at 17 verses where the ESV,
# which OpenBible follows, has 15 and 18. The table allows the longer reading.
OVERRIDES = {"Rom": {14: 23, 16: 27}, "3John": {1: 15}, "Rev": {12: 18}}

CHAPTER = re.compile(r"\\c\s+(\d+)")
VERSE = re.compile(r"\\v\s+(\d+)(?:-(\d+))?")


def count(usfm: str) -> list[int]:
    chapters: list[int] = []
    for line in usfm.splitlines():
        if m := CHAPTER.match(line):
            if int(m.group(1)) != len(chapters) + 1:
                raise SystemExit(f"chapters out of order: {line!r}")
            chapters.append(0)
        for m in VERSE.finditer(line):
            last = int(m.group(2) or m.group(1))  # a bridge "\v 3-4" ends at 4
            chapters[-1] = max(chapters[-1], last)
    return chapters


def main() -> None:
    # eBible.org refuses Python's default user agent.
    books: dict[str, list[int]] = {}
    for url, codes in ((URL, USFM_TO_OSIS), (DEUTERO_URL, DEUTERO)):
        request = urllib.request.Request(url, headers={"User-Agent": "history-globe-pipeline"})
        raw = urllib.request.urlopen(request).read()
        with zipfile.ZipFile(io.BytesIO(raw)) as z:
            for name in z.namelist():
                code = name[3:6]
                if name.endswith(".usfm") and code in codes:
                    books[codes[code]] = count(z.read(name).decode("utf-8-sig"))
    for book, chapters in OVERRIDES.items():
        for chapter, verses in chapters.items():
            books[book][chapter - 1] = verses
    missing = (set(USFM_TO_OSIS.values()) | set(DEUTERO.values())) - set(books)
    if missing:
        raise SystemExit(f"books missing from the download: {sorted(missing)}")
    order = [*USFM_TO_OSIS.values(), *DEUTERO.values()]
    rows = "\n".join(f'  {b if b.isidentifier() else repr(b).replace(chr(39), chr(34))}: [{", ".join(map(str, books[b]))}],' for b in order)
    OUT.write_text(
        "// Generated by pipeline/build_versification.py from the World English Bible\n"
        "// (public domain, eBible.org), with Rom 14 and 16 as in KJV and ESV and 3 John and\n"
        "// Rev 12 as in the ESV; 1-2 Maccabees from the KJV with its Apocrypha. Do not edit by hand.\n\n"
        "/** OSIS book id → number of verses in each chapter (English versification). */\n"
        "export const VERSES: Readonly<Record<string, readonly number[]>> = {\n"
        f"{rows}\n"
        "};\n",
        encoding="utf-8",
    )
    print(f"{len(books)} books, {sum(len(c) for c in books.values())} chapters, {sum(map(sum, books.values()))} verses")


if __name__ == "__main__":
    main()
